Repository hms-dbmi/service-workbench-on-aws, pull requests merged in 2022-10, with the labels that each got.

#48 Fixes for secure environments
  addons/addon-base-post-deployment/packages/base-post-deployment/lib/steps/add-auth-providers.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/create-cognito-user-pool-input-manifest.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/create-cognito-user-pool-schema.json
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/update-cognito-user-pool-input-manifest.js
  addons/addon-register/packages/register/lib/services/register-service.js
  addons/addon-register/packages/register/package.json
  main/config/settings/example.yml
  main/solution/post-deployment/config/infra/functions.yml
  main/solution/post-deployment/config/settings/.defaults.yml
  pnpm-lock.yaml
Labels: size/s

#49 Parameterize custom User Registration page
  addons/addon-base-post-deployment/packages/base-post-deployment/lib/steps/add-auth-providers.js
  addons/addon-base-rest-api/packages/base-controllers/lib/authentication-provider-public-controller.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/create-cognito-user-pool-schema.json
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js
  addons/addon-base-ui/packages/base-ui/src/helpers/settings.js
  addons/addon-base-ui/packages/base-ui/src/models/authentication/AuthenticationProviderPublicConfig.js
  addons/addon-register/packages/register/css/overrides.css
  addons/addon-register/packages/register/images/logo.png
  addons/addon-register/packages/register/lib/services/register-service.js
  addons/addon-register/packages/register/src/extend/withAuth.js
  addons/addon-register/packages/register/src/models/RegisterForm.js
  addons/addon-register/packages/register/src/parts/Register.js
  addons/addon-register/packages/register/src/plugins/app-component-plugin.js
  addons/addon-register/packages/register/src/plugins/app-context-items-plugin.js
  main/config/settings/example.yml
  main/solution/post-deployment/config/infra/functions.yml
  main/solution/post-deployment/config/saml-metadata/avillachlab_auth0_com-metadata.xml
  main/solution/post-deployment/config/settings/.defaults.yml
  main/solution/ui/config/environment/env-template.yml
  main/solution/ui/config/settings/.defaults.yml
Labels: size/m

#50 User registration page changes from aim-ahead branch
  .npmrc
  addons/addon-base-post-deployment/packages/base-post-deployment/lib/steps/add-auth-providers.js
  addons/addon-base-rest-api/packages/base-controllers/lib/authentication-provider-public-controller.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/create-cognito-user-pool-input-manifest.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/create-cognito-user-pool-schema.json
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js
  addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/update-cognito-user-pool-input-manifest.js
  addons/addon-base-ui/packages/base-ui/src/helpers/settings.js
  addons/addon-base-ui/packages/base-ui/src/models/authentication/AuthenticationProviderPublicConfig.js
  addons/addon-base-ui/packages/base-ui/src/parts/Login.js
  addons/addon-base/packages/services/lib/user/user-service.js
  addons/addon-register/packages/register/.babelrc
  addons/addon-register/packages/register/.eslintrc.json
  addons/addon-register/packages/register/.gitignore
  addons/addon-register/packages/register/.prettierrc.json
  addons/addon-register/packages/register/css/overrides.css
  addons/addon-register/packages/register/images/SWB.png
  addons/addon-register/packages/register/jest.config.js
  addons/addon-register/packages/register/jsconfig.json
  addons/addon-register/packages/register/lib/controllers/register-controller.js
  addons/addon-register/packages/register/lib/plugins/routes-plugin.js
  addons/addon-register/packages/register/lib/plugins/services-plugin.js
  addons/addon-register/packages/register/lib/schemas/register-user.json
  addons/addon-register/packages/register/lib/services/register-service.js
  addons/addon-register/packages/register/package.json
  addons/addon-register/packages/register/setup-tests.js
  addons/addon-register/packages/register/src/extend/withAuth.js
  addons/addon-register/packages/register/src/helpers/api.js
  addons/addon-register/packages/register/src/models/RegisterForm.js
  addons/addon-register/packages/register/src/parts/App.js
  addons/addon-register/packages/register/src/parts/Register.js
  addons/addon-register/packages/register/src/plugins/app-component-plugin.js
  addons/addon-register/packages/register/src/plugins/app-context-items-plugin.js
  addons/addon-register/packages/register/src/plugins/routes-plugin.js
  main/config/settings/example.yml
  main/solution/backend/config/infra/functions.yml
  main/solution/backend/package.json
  main/solution/backend/src/lambdas/api-handler/plugins/plugin-registry.js
  main/solution/infrastructure/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/functions.yml
  main/solution/post-deployment/config/infra/registrationWAF.yml
  main/solution/post-deployment/config/saml-metadata/avillachlab_auth0_com-metadata.xml
  main/solution/post-deployment/config/settings/.defaults.yml
  main/solution/post-deployment/serverless.yml
  main/solution/ui/config/environment/env-template.yml
  main/solution/ui/config/settings/.defaults.yml
  main/solution/ui/package.json
  main/solution/ui/src/index.js
  main/solution/ui/src/plugins/plugin-registry.js
  openapi.yaml
  pnpm-lock.yaml
Labels: size/xl

#51 Add WorkspaceName Tag for user notification
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-config-vars-service.js
Labels: size/xs

#53 Bugfix/Update files for Code Build.
  addons/addon-base-rest-api/packages/base-controllers/lib/__tests__/__fixtures__/authentication-provider-configs.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/start-sagemaker-environment-sc.test.js
  addons/addon-register/packages/register/src/parts/Register.js
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
Labels: size/s
