Repository hms-dbmi/service-workbench-on-aws, pull requests merged in 2022-11, with the labels that each got.

#54 Updates build pipeline and image
  main/cicd/cicd-pipeline/config/buildspec/buildspec.yml
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
Labels: enhancement, size/s

#55 Add permissions to add tags
  main/solution/post-deployment/config/infra/cloudformation.yml
Labels: size/xs

#56 Pulling in BCH dev changes to prod
  addons/addon-base-ui/packages/base-ui/images/favicon-32x32.png
  addons/addon-base-ui/packages/base-ui/images/favicon.ico
  addons/addon-base-ui/packages/base-ui/images/login-image.gif
  addons/addon-base-ui/packages/base-ui/images/logo-image.png
  main/cicd/cicd-pipeline/config/buildspec/buildspec.yml
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/cloudformation.yml
Labels: size/s

#57 Align aim-ahead dbmi dev and prod
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-config-vars-service.js
  addons/addon-base-rest-api/packages/base-controllers/lib/__tests__/__fixtures__/authentication-provider-configs.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/start-sagemaker-environment-sc.test.js
  addons/addon-register/packages/register/src/parts/Register.js
  main/cicd/cicd-pipeline/config/buildspec/buildspec.yml
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
  main/solution/post-deployment/config/infra/cloudformation.yml
Labels: size/s

#59 Increase WAF rate from 500 to 4000
  main/solution/post-deployment/serverless.yml
Labels: size/xs

#61 Update waf permissions to wafv2.
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
Labels: size/xs

#62 Align aim-ahead-dbmi dev and prod
  main/cicd/cicd-pipeline/config/infra/cloudformation.yml
  main/solution/post-deployment/serverless.yml
Labels: size/xs
