Repository hms-dbmi/service-workbench-on-aws, pull requests merged in 2023-07, with the labels that each got.

#106 waf variable with default set
  main/solution/post-deployment/config/settings/.defaults.yml
  main/solution/post-deployment/serverless.yml
Labels: size/xs

#107 pull in byon-main changes.
  CHANGELOG.md
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-linux-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-windows-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/emr-cluster.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml
  main/solution/post-deployment/config/environment-files/windows/get_security_agents.ps1
  main/solution/post-deployment/config/settings/.defaults.yml
  main/solution/post-deployment/serverless.yml
Labels: size/m

#110 Feature/show workspace with revoked type
  CHANGELOG.md
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/ScEnvironmentCard.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/ScEnvironmentDetailPage.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/__tests__/ScEnvironmentCard.test.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/setup/Logos.js
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/setup/SelectEnvTypeStep.js
Labels: size/m

#109 Feature/rapids kernel
  CHANGELOG.md
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/plugins/cfn-templates-plugin.js
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/application-load-balancer.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/ec2-linux-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/ec2-rstudio-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/ec2-windows-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/sagemaker-notebook-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-rstudio-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml
  addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/provision-environment/provision-environment.js
  main/solution/post-deployment/config/environment-files/install_kernel.sh
  main/solution/post-deployment/config/environment-files/kernels/rapids_23.06.yml
Labels: size/xl
