Repository hms-dbmi/service-workbench-on-aws, pull requests merged in 2023-09, with the labels that each got.

#127 Fix quotes I messed up
  addons/addon-custom/packages/main/data/terms.js
Labels: size/xs

#128 Downgrade python runtime version to version code commit uses.
  main/cicd/cicd-pipeline/config/buildspec/buildspec-int-tests.yml
  main/cicd/cicd-pipeline/config/buildspec/buildspec-uninstall.yml
  main/cicd/cicd-pipeline/config/buildspec/buildspec.yml
Labels: size/xs

#129 Update linting whitespace.
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/advanced/ScEnvAdvancedList.js
  addons/addon-base-ui/packages/base-ui/src/render-utils.js
Labels: size/xs

#126 feat: Added support for multiple ALBs
  .pnpm-debug.log
  addons/addon-base-raas/packages/base-raas-cfn-templates/.pnpm-debug.log
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/application-load-balancer.cfn.yml
  addons/addon-base-raas/packages/base-raas-rest-api/lib/plugins/services-plugin.js
  addons/addon-base-raas/packages/base-raas-services/lib/alb/__tests__/alb-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/alb/alb-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/plugins/__tests__/env-provisioning-plugin.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/plugins/env-provisioning-plugin.js
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-environment-sc.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/create-load-balancer.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-environment-sc.json
  addons/addon-base-raas/packages/base-raas-services/lib/schema/update-load-balancer.json
  addons/addon-base-raas/packages/base-raas-services/package.json
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/check-launch-dependency.test.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/terminate-launch-dependency.test.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/check-launch-dependency/check-launch-dependency.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/terminate-launch-dependency/terminate-launch-dependency.js
  addons/addon-user-id-upgrade/packages/user-id-upgrade-post-deployment/lib/plugins/services-plugin.js
  main/solution/.pnpm-debug.log
  main/solution/backend/config/infra/cloudformation.yml
  main/solution/backend/config/infra/functions.yml
  main/solution/backend/config/settings/.defaults.yml
  main/solution/post-deployment/config/infra/cloudformation.yml
  main/solution/post-deployment/config/settings/.defaults.yml
  pnpm-lock.yaml
  scripts/migration-scripts/v5.2.12/config.js
  scripts/migration-scripts/v5.2.12/migrate-albdetails-to-loadbalancer-table/migrate.js
  scripts/migration-scripts/v5.2.12/updating-alb-id-to-rstudio/migrate.js
Labels: enhancement

#135 Update changelog and remove misc log files.
  .pnpm-debug.log
  CHANGELOG.md
  addons/addon-base-raas/packages/base-raas-cfn-templates/.pnpm-debug.log
  main/solution/.pnpm-debug.log
Labels: size/xl
